// Code generated by sqlc. DO NOT EDIT.

package launchpad

import ()

type AptosLaunchpad struct {
	ID            int64  `json:"id"`
	UserAddress   string `json:"user_address"`
	ModuleAddress string `json:"module_address"`
	Price         int32  `json:"price"`
	CreatedAt     string `json:"created_at"`
}

type EvmLaunchpad struct {
	ID         int64  `json:"id"`
	EoaAddress string `json:"eoa_address"`
	CaAddress  string `json:"ca_address"`
	ChainID    int32  `json:"chain_id"`
	Price      int32  `json:"price"`
	CreatedAt  string `json:"created_at"`
}
