// Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/evmLaunchpad/CreateNewLaunchPad": {
            "post": {
                "description": "Create New launchpad In Evm",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "EVM Launchpad"
                ],
                "summary": "Create New launchpad",
                "responses": {
                    "default": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/models.EvmLaunchpaSuccessResponse"
                        }
                    }
                }
            }
        },
        "/evmLaunchpad/GetMyAllLaunchpad": {
            "get": {
                "description": "getMy All EvmLaunchpad",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "EVM Launchpad"
                ],
                "summary": "getMy All EvmLaunchpad",
                "parameters": [
                    {
                        "type": "string",
                        "description": "input my Eoa Address",
                        "name": "eoa_address",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "default": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/models.EvmLaunchpaSuccessResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.EvmLaunchpaSuccessResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
