definitions:
  models.EvmLaunchpaSuccessResponse:
    properties:
      message:
        type: string
      status:
        type: integer
    type: object
  models.EvmLaunchpad:
    properties:
      contract_address:
        type: string
      eoa_address:
        type: string
      meta_data_uri:
        type: string
      network_chain_id:
        type: integer
      price:
        minimum: 0
        type: integer
    required:
    - contract_address
    - eoa_address
    - meta_data_uri
    - network_chain_id
    - price
    type: object
info:
  contact: {}
paths:
  /evmLaunchpad/CreateNewLaunchPad:
    post:
      description: Create New launchpad In Evm
      produces:
      - application/json
      responses:
        default:
          description: ""
          schema:
            $ref: '#/definitions/models.EvmLaunchpaSuccessResponse'
      summary: Create New launchpad
      tags:
      - EVM Launchpad
  /evmLaunchpad/GetLaunchPad:
    get:
      description: get EvmLaunchpad
      parameters:
      - description: Input ca Address
        in: query
        name: eoa_address
        required: true
        type: string
      produces:
      - application/json
      responses:
        default:
          description: ""
          schema:
            $ref: '#/definitions/models.EvmLaunchpad'
      summary: get EvmLaunchpad
      tags:
      - EVM Launchpad
  /evmLaunchpad/GetMyAllLaunchpad:
    get:
      description: getMy All EvmLaunchpad
      parameters:
      - description: input my Eoa Address
        in: query
        name: eoa_address
        required: true
        type: string
      produces:
      - application/json
      responses:
        default:
          description: ""
          schema:
            items:
              $ref: '#/definitions/models.EvmLaunchpad'
            type: array
      summary: getMy All EvmLaunchpad
      tags:
      - EVM Launchpad
swagger: "2.0"
