name: my-ci

on: push

jobs:
  go-version-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.19.4"
          cache: true
      - name: Display Go version
        run: go version

  go-install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: go mod download
